
# Configuração do datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=quarkus
quarkus.datasource.password=senha123
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/studioDB

# Hibernate ORM (se estiver usando Panache/JPA)
quarkus.hibernate-orm.database.generation=update
